Repository LT-Students/DigitalOffice, pull requests merged in 2020-08, with the labels that each got.

#20 ProjectService_GetProjectInfo
  DigitalOffice/Services/ProjectService/Commands/GetProjectInfoByIdCommand.cs
  DigitalOffice/Services/ProjectService/Commands/Interfaces/IGetProjectInfoByIdCommand.cs
  DigitalOffice/Services/ProjectService/Controllers/ProjectController.cs
  DigitalOffice/Services/ProjectService/Database/Entities/DbProject.cs
  DigitalOffice/Services/ProjectService/Database/Entities/DbProject.cs~HEAD
  DigitalOffice/Services/ProjectService/Database/Entities/DbProject.cs~ProjectService_CreateProject
  DigitalOffice/Services/ProjectService/Database/Entities/DbProjectFile.cs~HEAD
  DigitalOffice/Services/ProjectService/Database/Entities/DbProjectFile.cs~ProjectService_CreateProject
  DigitalOffice/Services/ProjectService/Database/Entities/DbProjectManagerUser.cs~HEAD
  DigitalOffice/Services/ProjectService/Database/Entities/DbProjectManagerUser.cs~ProjectService_CreateProject
  DigitalOffice/Services/ProjectService/Database/Entities/DbProjectWorkerUser.cs~HEAD
  DigitalOffice/Services/ProjectService/Database/Entities/DbProjectWorkerUser.cs~ProjectService_CreateProject
  DigitalOffice/Services/ProjectService/Database/Migrations/ProjectServiceDbContextModelSnapshot.cs
  DigitalOffice/Services/ProjectService/Mappers/Interfaces/IMapper.cs
  DigitalOffice/Services/ProjectService/Mappers/ProjectMapper.cs
  DigitalOffice/Services/ProjectService/Models/Project.cs
  DigitalOffice/Services/ProjectService/Program.cs
  DigitalOffice/Services/ProjectService/Repositories/Interfaces/IProjectRepository.cs
  DigitalOffice/Services/ProjectService/Repositories/ProjectRepository.cs
  DigitalOffice/Services/ProjectService/Startup.cs
  DigitalOffice/Tests/ProjectServiceTests/CommandsTests/GetProjectInfoByIdCommandTests.cs
  DigitalOffice/Tests/ProjectServiceTests/MappersTests/ProjectMapperTests.cs
  DigitalOffice/Tests/ProjectServiceTests/ProjectServiceUnitTests.csproj
  DigitalOffice/Tests/ProjectServiceTests/RepositoriesTests/GetProjectInfoByIdRepositoryTests.cs
  DigitalOffice/Tests/ProjectServiceTests/UnitTestLibrary/SerializerAssert.cs
Labels: feature

#39 UserService_FixMapperTest
  DigitalOffice/Tests/UserServiceTests/Mappers/UserCreateRequestToDbUserMapperTests.cs
Labels: refactor

#38 FileService_GetFile
  DigitalOffice/Services/FileService/Commands/GetFileByIdCommand.cs
  DigitalOffice/Services/FileService/Commands/Interfaces/IGetFileByIdCommand.cs
  DigitalOffice/Services/FileService/Controllers/FileController.cs
  DigitalOffice/Services/FileService/Mappers/FileMapper.cs
  DigitalOffice/Services/FileService/Properties/launchSettings.json
  DigitalOffice/Services/FileService/Repositories/FileRepository.cs
  DigitalOffice/Services/FileService/Repositories/Interfaces/IFileRepository.cs
  DigitalOffice/Services/FileService/Startup.cs
  DigitalOffice/Tests/FileServiceTests/Commands/GetFileByIdCommandTests.cs
  DigitalOffice/Tests/FileServiceTests/Repositories/AddNewFileRepositoryTests.cs
  DigitalOffice/Tests/FileServiceTests/Repositories/GetFileByIdRepositoryTests.cs
  DigitalOffice/Tests/ProjectServiceTests/CommandsTests/GetProjectInfoByIdCommandTests.cs
  DigitalOffice/Tests/ProjectServiceTests/RepositoriesTests/GetProjectInfoByIdRepositoryTests.cs
Labels: feature

#30 TimeManagementService_LeaveTime_Create
  DigitalOffice/Services/TimeManagementService/Commands/CreateLeaveTimeCommand.cs
  DigitalOffice/Services/TimeManagementService/Commands/Interfaces/ICreateLeaveTimeCommand.cs
  DigitalOffice/Services/TimeManagementService/Controllers/TimeManagementController.cs
  DigitalOffice/Services/TimeManagementService/Database/Entities/DbLeaveTime.cs
  DigitalOffice/Services/TimeManagementService/Database/TimeManagementDbContext.cs
  DigitalOffice/Services/TimeManagementService/Mappers/LeaveTimeMapper.cs
  DigitalOffice/Services/TimeManagementService/Models/CreateLeaveTimeRequest.cs
  DigitalOffice/Services/TimeManagementService/Repositories/Interfaces/ILeaveTimeRepository.cs
  DigitalOffice/Services/TimeManagementService/Repositories/LeaveTimeRepository.cs
  DigitalOffice/Services/TimeManagementService/Startup.cs
  DigitalOffice/Services/TimeManagementService/Validators/CreateLeaveTimeRequestValidator.cs
  DigitalOffice/Tests/TimeManagementServiceTests/Commands/CreateLeaveTimeCommandTests.cs
  DigitalOffice/Tests/TimeManagementServiceTests/Commands/CreateWorkTimeCommandTests.cs
  DigitalOffice/Tests/TimeManagementServiceTests/Mappers/LeaveTimeMapperTests.cs
  DigitalOffice/Tests/TimeManagementServiceTests/Repositories/LeaveTimeRepositoryTests.cs
  DigitalOffice/Tests/TimeManagementServiceTests/Repositories/WorkTimeRepositoryTests.cs
  DigitalOffice/Tests/TimeManagementServiceTests/Validators/CreateLeaveTimeRequestValidatorTests.cs
  DigitalOffice/Tests/TimeManagementServiceTests/Validators/CreateWorkTimeRequestValidatorTests.cs
Labels: feature

#46 CompanyService_GetPositionById
  DigitalOffice/Services/CompanyService/Commands/GetPositionByIdCommand.cs
  DigitalOffice/Services/CompanyService/Commands/Interfaces/IGetPositionByIdCommand.cs
  DigitalOffice/Services/CompanyService/CompanyService.csproj
  DigitalOffice/Services/CompanyService/Controllers/CompanyController.cs
  DigitalOffice/Services/CompanyService/Mappers/PositionMapper.cs
  DigitalOffice/Services/CompanyService/Models/Position.cs
  DigitalOffice/Services/CompanyService/Repositories/CompanyRepository.cs
  DigitalOffice/Services/CompanyService/Repositories/Interfaces/ICompanyRepository.cs
  DigitalOffice/Services/CompanyService/Startup.cs
  DigitalOffice/Tests/CompanyServiceTests/Commands/GetPositionByIdCommandTests.cs
  DigitalOffice/Tests/CompanyServiceTests/Controllers/CompanyControllerTests.cs
  DigitalOffice/Tests/CompanyServiceTests/Mappers/PositionMappersTests.cs
  DigitalOffice/Tests/CompanyServiceTests/Repositories/CompanyRepositoryTests.cs
  DigitalOffice/Tests/FileServiceTests/UnitTestLibrary/SerializerAssert.cs
Labels: feature

#47 CompanyService_AddPosition
  DigitalOffice/Services/CompanyService/Commands/AddPositionCommand.cs
  DigitalOffice/Services/CompanyService/Commands/Interfaces/IAddPositionCommand.cs
  DigitalOffice/Services/CompanyService/Controllers/CompanyController.cs
  DigitalOffice/Services/CompanyService/Mappers/PositionMapper.cs
  DigitalOffice/Services/CompanyService/Models/AddPositionRequest.cs
  DigitalOffice/Services/CompanyService/Repositories/CompanyRepository.cs
  DigitalOffice/Services/CompanyService/Repositories/Interfaces/ICompanyRepository.cs
  DigitalOffice/Services/CompanyService/Startup.cs
  DigitalOffice/Services/CompanyService/Validators/AddPositionRequestValidator.cs
  DigitalOffice/Tests/CompanyServiceTests/Commands/AddPositionCommandTests.cs
  DigitalOffice/Tests/CompanyServiceTests/CompanyServiceUnitTests.csproj
  DigitalOffice/Tests/CompanyServiceTests/Controllers/CompanyControllerTests.cs
  DigitalOffice/Tests/CompanyServiceTests/Mappers/PositionMappersTests.cs
  DigitalOffice/Tests/CompanyServiceTests/Repositories/CompanyRepositoryTests.cs
  DigitalOffice/Tests/CompanyServiceTests/Validators/AddPositionRequestValidatorTests.cs
Labels: feature

#51 CompanyService_GetCompanyById
  DigitalOffice/Services/CompanyService/Commands/GetCompanyByIdCommand.cs
  DigitalOffice/Services/CompanyService/Commands/Interfaces/IGetCompanyByIdCommand.cs
  DigitalOffice/Services/CompanyService/Controllers/CompanyController.cs
  DigitalOffice/Services/CompanyService/Mappers/CompanyMapper.cs
  DigitalOffice/Services/CompanyService/Models/Company.cs
  DigitalOffice/Services/CompanyService/Repositories/CompanyRepository.cs
  DigitalOffice/Services/CompanyService/Repositories/Interfaces/ICompanyRepository.cs
  DigitalOffice/Services/CompanyService/Startup.cs
  DigitalOffice/Tests/CompanyServiceTests/Commands/GetCompanyByIdCommandTests.cs
  DigitalOffice/Tests/CompanyServiceTests/Mappers/CompanyMapperTests.cs
  DigitalOffice/Tests/CompanyServiceTests/Repositories/CompanyRepositoryTests.cs
Labels: feature

#41 UserService_GetUserByEmail
  DigitalOffice/Services/UserService/Commands/GetUserByEmailCommand.cs
  DigitalOffice/Services/UserService/Commands/Interfaces/IGetUserByEmailCommand.cs
  DigitalOffice/Services/UserService/Controllers/UserController.cs
  DigitalOffice/Services/UserService/Models/User.cs
  DigitalOffice/Services/UserService/Startup.cs
  DigitalOffice/Services/UserService/Validators/GetUserByEmailValidator.cs
  DigitalOffice/Tests/UserServiceTests/Commands/GetUserByEmailCommandTests.cs
  DigitalOffice/Tests/UserServiceTests/Controllers/UserControllerTests.cs
  DigitalOffice/Tests/UserServiceTests/Repositories/UserRepositoryTests.cs
  DigitalOffice/Tests/UserServiceTests/Validators/GetUserByEmailValidatorTests.cs
Labels: feature

#50 CompanyService_GetPositionsList
  DigitalOffice/Services/CompanyService/Commands/GetPositionsListCommand.cs
  DigitalOffice/Services/CompanyService/Commands/Interfaces/IGetPositionsListCommand.cs
  DigitalOffice/Services/CompanyService/Controllers/CompanyController.cs
  DigitalOffice/Services/CompanyService/Repositories/CompanyRepository.cs
  DigitalOffice/Services/CompanyService/Repositories/Interfaces/ICompanyRepository.cs
  DigitalOffice/Services/CompanyService/Startup.cs
  DigitalOffice/Tests/CompanyServiceTests/Commands/GetPositionsListCommandTests.cs
  DigitalOffice/Tests/CompanyServiceTests/Repositories/CompanyRepositoryTests.cs
Labels: feature

#27 UserService_UserInfo_RabbitMq
  DigitalOffice/Services/UserService/Broker/Consumers/GetUserInfoConsumer.cs
  DigitalOffice/Services/UserService/Broker/Requests/IGetUserInfoRequest.cs
  DigitalOffice/Services/UserService/Broker/Requests/IGetUserPositionRequest.cs
  DigitalOffice/Services/UserService/Broker/Responses/IUserInfoResponse.cs
  DigitalOffice/Services/UserService/Broker/Responses/IUserPositionResponse.cs
  DigitalOffice/Services/UserService/Mappers/Interfaces/IMapper.cs
  DigitalOffice/Services/UserService/Mappers/UserMapper.cs
  DigitalOffice/Services/UserService/Startup.cs
  DigitalOffice/Tests/UserServiceTests/Consumers/GetUserInfoConsumerTests.cs
  DigitalOffice/Tests/UserServiceTests/Mappers/UserMapperTests.cs
  DigitalOffice/Tests/UserServiceTests/Utils/InheritedUserPositionResponse.cs
Labels: feature

#60 AuthenticationService_CheckToken
  DigitalOffice/LT.DigitalOffice.sln
  DigitalOffice/Services/AuthenticationService/Broker/Consumers/UserJwtConsumer.cs
  DigitalOffice/Services/AuthenticationService/Broker/Requests/IUserJwtRequest.cs
  DigitalOffice/Services/AuthenticationService/Startup.cs
  DigitalOffice/Services/AuthenticationService/Token/Interfaces/IJwtSigningDecodingKey.cs
  DigitalOffice/Services/AuthenticationService/Token/Interfaces/IJwtSigningEncodingKey.cs
  DigitalOffice/Services/AuthenticationService/Token/Interfaces/IJwtValidator.cs
  DigitalOffice/Services/AuthenticationService/Token/JwtValidator.cs
  DigitalOffice/Services/AuthenticationService/appsettings.json
  DigitalOffice/Tests/AuthenticationServiceTests/AuthenticationServiceUnitTests.csproj
  DigitalOffice/Tests/AuthenticationServiceTests/Broker/Consumers/UserJwtConsumerTests.cs
  DigitalOffice/Tests/AuthenticationServiceTests/Commands/UserLoginCommandTests.cs
  DigitalOffice/Tests/AuthenticationServiceTests/Token/JwtValidationTests.cs
  DigitalOffice/Tests/ProjectServiceTests/UnitTestLibrary/SerializerAssert.cs
Labels: feature

#37 CompanyService_ChangeCompany
  DigitalOffice/Services/CompanyService/Commands/EditCompanyCommand.cs
  DigitalOffice/Services/CompanyService/Commands/Interfaces/IEditCompanyCommand.cs
  DigitalOffice/Services/CompanyService/Controllers/CompanyController.cs
  DigitalOffice/Services/CompanyService/Mappers/CompanyMapper.cs
  DigitalOffice/Services/CompanyService/Models/EditCompanyRequest.cs
  DigitalOffice/Services/CompanyService/Repositories/CompanyRepository.cs
  DigitalOffice/Services/CompanyService/Repositories/Interfaces/ICompanyRepository.cs
  DigitalOffice/Services/CompanyService/Startup.cs
  DigitalOffice/Services/CompanyService/Validators/AddCompanyValidator.cs
  DigitalOffice/Services/CompanyService/Validators/EditCompanyValidator.cs
  DigitalOffice/Tests/CompanyServiceTests/Commands/EditCompanyCommandTests.cs
  DigitalOffice/Tests/CompanyServiceTests/Mappers/CompanyMapperTests.cs
  DigitalOffice/Tests/CompanyServiceTests/Repositories/CompanyRepositoryTests.cs
  DigitalOffice/Tests/CompanyServiceTests/Validators/EditCompanyValidatorTests.cs
Labels: feature

#65 NameConvention
  NameConvention.md
Labels: docs

#33 FileService_GetFile_RabbitMq
  Services/FileService/Broker/Consumers/GetFileConsumer.cs
  Services/FileService/Broker/Requests/IGetFileRequest.cs
  Services/FileService/Broker/Responses/IFileResponse.cs
  Services/FileService/Controllers/FileController.cs
  Services/FileService/FileService.csproj
  Services/FileService/Program.cs
  Services/FileService/Properties/launchSettings.json
  Services/FileService/Startup.cs
  Services/FileService/appsettings.json
  Services/ProjectService/Broker/Requests/IGetFileRequest.cs
  Services/ProjectService/Broker/Responses/IFileResponse.cs
  Services/ProjectService/Commands/GetProjectByIdCommand.cs
  Services/ProjectService/Controllers/ProjectController.cs
  Services/ProjectService/Program.cs
  Services/ProjectService/ProjectService.csproj
  Services/ProjectService/Startup.cs
  Services/ProjectService/appsettings.json
  Services/UserService/Broker/Requests/IGetFileRequest.cs
  Services/UserService/Broker/Responses/IFileResponse.cs
  Services/UserService/Controllers/UserController.cs
  Services/UserService/Startup.cs
  Shared/Kernel/Broker/IOperationResult.cs
  Tests/FileServiceTests/Consumers/GetFileConsumerTests.cs
  Tests/ProjectServiceTests/Commands/GetProjectByIdCommandTests.cs
  Tests/ProjectServiceTests/Repositories/GetProjectByIdRepositoryTests.cs
Labels: feature

#66 ProjectService_DisableUsers
  Services/ProjectService/Commands/DisableWorkersInProjectCommand.cs
  Services/ProjectService/Commands/EditProjectByIdCommand.cs
  Services/ProjectService/Commands/GetProjectInfoByIdCommand.cs
  Services/ProjectService/Commands/Interfaces/IDisableWorkersInProject.cs
  Services/ProjectService/Controllers/ProjectController.cs
  Services/ProjectService/Models/WorkersIdsInProjectRequest.cs
  Services/ProjectService/Repositories/Interfaces/IProjectRepository.cs
  Services/ProjectService/Repositories/ProjectRepository.cs
  Services/ProjectService/Startup.cs
  Services/ProjectService/Validators/WorkersProjectIdsValidator.cs
  Tests/ProjectServiceTests/Repositories/DisableWorkersInProjectRepositoryTests.cs
  Tests/ProjectServiceTests/Validators/CreateNewProjectRequestValidatorTests.cs
  Tests/ProjectServiceTests/Validators/WorkersProjectIdsValidatorTests.cs
Labels: feature
